services:
  - type: web
    name: proj
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
